### ISSUE TITLE
api endpoint not returning expected results

### ISSUE THREAD

**Issue by kdaker** [picsoung/tf-lambda-limit-one-entry#2]
Created a test account and going through the steps in the readme, got stuck on step 6. Getting the following response:
```
{"code":"NOT_FOUND","description":"Endpoint not found"}
```
The form I'm trying is public but I do not have a pro account.

URL:
https://api.typeform.com/to/MNaR5o

**Comment by picsoung** [comment]
Hi @kdaker 

Thanks for your comment.
it was a mistake in the `README.md` file, it should be `https://api.typeform.com/forms/MNaR5o` instead.
I corrected it.
Thanks
